import { useEffect, useState } from "react";
import { ArrowRight, BriefcaseBusiness, GitBranch, Network, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { getJson } from "../api";
import { PageIntro, StatusBanner, TagList } from "../components/Layout";

type Emerging = { candidate_id: string; candidate_name: string; status: string; jd_count: number; company_count: number; source_count: number; first_seen: string; last_seen: string; core_skills: string[]; distinguishing_skills: string[]; similar_existing_jobs: string[]; notice: string };
type Change = { job_title: string; new_skills: string[]; growing_skills: string[]; stable_skills: string[]; declining_skills: string[]; clues: string[]; support_jd_ids: string[]; sample_insufficient: boolean; sample_status: string };
type Payload = { batch_id: string; graph_version: string; updated_at: string; summary: Record<string, number>; emerging_jobs: Emerging[]; capability_changes: Change[]; cross_validation: Array<{ trend: string; jd_evidence_ids: string[]; policy_evidence_ids: string[]; report_evidence_ids: string[]; summary: string; strength: string }> };

export default function JobChangesPage() {
  const [data,setData]=useState<Payload|null>(null); const [selected,setSelected]=useState<Emerging|null>(null);
  useEffect(()=>{void getJson<Payload>("/api/job-changes", "/data/job_changes.json").then(r=>setData(r.data));},[]);
  const stats=[["jd_count","新增JD"],["emerging_candidate_count","新兴岗位候选"],["changed_job_count","能力变化岗位"],["new_job_node_count","新增岗位节点"],["new_skill_node_count","新增技能节点"],["new_relation_count","新增图谱关系"]] as const;
  return <><PageIntro kicker="Baseline · Incremental Batch · Change Detection" title="岗位变化：原来、本次新增与现在" description="使用真实增量招聘证据识别新兴岗位候选和既有岗位能力变化，并同步更新 Graph V2。"/>
    <StatusBanner>本次数据更新：{data?.batch_id || "加载中"} · {data?.graph_version || "—"} · {data?.updated_at || "—"}</StatusBanner>
    <section className="metric-grid compact">{stats.map(([key,label])=><article className="metric-card" key={key}><div className="metric-value">+{data?.summary[key] ?? "—"}</div><div className="metric-label">{label}</div></article>)}</section>
    <article className="panel change-flow"><div><small>原来</small><b>Graph V1</b><span>正式冻结基准图谱</span></div><ArrowRight/><div><small>本次新增</small><b>+{data?.summary.jd_count ?? 0} JD</b><span>6份真实数据文件</span></div><ArrowRight/><div><small>现在</small><b>{data?.graph_version || "Graph V2"}</b><span>岗位与技能关系动态更新</span></div></article>
    <section className="section-heading"><div><p className="kicker">A. 新岗位发现</p><h2>新兴岗位候选</h2></div><Sparkles/></section>
    <div className="change-card-grid">{data?.emerging_jobs.map(item=><article className="panel change-card" key={item.candidate_id}><div className="candidate-top"><span>{item.candidate_id}</span><em className="confidence medium">{item.status}</em></div><h2>{item.candidate_name}</h2><div className="candidate-stats"><span>{item.jd_count}<small>JD</small></span><span>{item.company_count}<small>企业</small></span><span>{item.source_count}<small>来源</small></span></div><p>{item.first_seen || "暂无"} 至 {item.last_seen || "暂无"}</p><TagList values={item.core_skills.slice(0,6)}/><button onClick={()=>setSelected(item)}>查看定义与证据 <ArrowRight size={14}/></button></article>)}</div>
    <section className="section-heading"><div><p className="kicker">B. 既有岗位能力变化</p><h2>能力要求前后对比</h2></div><BriefcaseBusiness/></section>
    <div className="change-list">{data?.capability_changes.map(item=><article className="panel" key={item.job_title}><div className="panel-title"><span>{item.job_title}</span><small>{item.support_jd_ids.length} 条支撑JD</small></div><StatusBanner tone={item.sample_insufficient?"warning":"info"}>{item.sample_status}</StatusBanner><div className="capability-grid"><div><h4>新增技能</h4><TagList values={item.new_skills} empty="暂无可靠新增"/></div><div><h4>增强技能</h4><TagList values={item.growing_skills} empty="暂无可靠增强"/></div><div><h4>稳定技能</h4><TagList values={item.stable_skills} empty="暂无可靠结论"/></div><div><h4>变化线索</h4><TagList values={item.clues} empty="暂无"/></div></div><p className="evidence-copy">Evidence：{item.support_jd_ids.join("、")}</p></article>)}</div>
    <section className="section-heading"><div><p className="kicker">C / D. 图谱变化</p><h2>新增技能与关系已进入动态能力图谱</h2></div><Network/></section><article className="panel graph-change-callout"><GitBranch/><div><b>Graph V1 → {data?.graph_version || "Graph V2"}</b><p>新增岗位、技能与岗位—技能关系均带 NEW 标记；已有关系收到新 Evidence 时带 UPDATED 标记。</p></div><Link className="primary-button" to="/graph">查看动态图谱</Link></article>
    <article className="panel"><div className="panel-title"><span>多源交叉证据链</span><small>JD为核心证据，政策/报告仅作佐证</small></div><div className="evidence-table">{data?.cross_validation.map(item=><div className="evidence-chain" key={item.trend}><b>{item.trend}</b><span>JD {item.jd_evidence_ids.length} 条 + 政策 {item.policy_evidence_ids.length} 条 + 行业报告 {item.report_evidence_ids.length} 条</span><small>{item.summary}</small><em>综合证据强度：{item.strength}</em></div>)}</div></article>
    {selected?<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p className="kicker">{selected.candidate_id} · {selected.status}</p><h1>{selected.candidate_name}</h1><h3>数据证据</h3><p>招聘JD {selected.jd_count} 条 · 企业 {selected.company_count} 家 · 来源 {selected.source_count} 个</p><h3>时间</h3><p>首次发现 {selected.first_seen || "暂无数据"} · 最近出现 {selected.last_seen || "暂无数据"}</p><h3>核心技能</h3><TagList values={selected.core_skills}/><h3>差异技能</h3><TagList values={selected.distinguishing_skills}/><h3>相似既有岗位</h3><TagList values={selected.similar_existing_jobs}/><StatusBanner tone="warning">{selected.notice}</StatusBanner></aside></div>:null}
  </>;
}
