import { useEffect, useState } from "react";
import { ArrowRight, GitBranch, Network, Sparkles, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { getJson } from "../api";
import { PageIntro, StatusBanner, TagList } from "../components/Layout";

type Emerging = { candidate_id: string; candidate_name: string; status: string; jd_count: number; company_count: number; source_count: number; first_seen: string; last_seen: string; core_skills: string[]; distinguishing_skills: string[]; similar_existing_jobs: string[]; notice: string };
type Period = { label: string; jd_count: number; company_count: number; support_jd_ids: string[] };
type SkillChange = { skill_name: string; early_count: number; early_frequency: number|null; recent_count: number; recent_frequency: number|null; direction: string };
type Change = { job_title: string; periods: Period[]; early_period: Period; recent_period: Period; trend: string; skill_changes: SkillChange[]; new_skills: string[]; growing_skills: string[]; stable_skills: string[]; declining_skills: string[]; clues: string[]; support_jd_ids: string[]; sample_insufficient: boolean; sample_status: string };
type Payload = { batch_id: string; graph_version: string; updated_at: string; summary: Record<string, number>; emerging_jobs: Emerging[]; capability_changes: Change[]; cross_validation: Array<{ trend: string; jd_evidence_ids: string[]; policy_evidence_ids: string[]; report_evidence_ids: string[]; summary: string; strength: string }> };

export default function JobChangesPage() {
  const [data,setData]=useState<Payload|null>(null); const [selected,setSelected]=useState<Emerging|null>(null);
  useEffect(()=>{void getJson<Payload>("/api/job-changes", "/data/job_changes.json").then(r=>setData(r.data));},[]);
  const stats=[["emerging_candidate_count","新兴岗位候选"],["changed_job_count","有时间对比岗位"],["new_skill_node_count","本次识别技能"],["new_relation_count","图谱新增关系"]] as const;
  return <><PageIntro kicker="岗位时间演化 · 技能要求变化 · Evidence 追溯" title="岗位变化：同一岗位过去需要什么，现在需要什么" description="按时间窗口比较同一岗位的招聘数量、企业数量和技能结构。数据不足时只展示变化线索，不作显著趋势判断。"/>
    <StatusBanner>本次数据更新：{data?.batch_id || "加载中"} · {data?.graph_version || "—"} · {data?.updated_at || "—"}</StatusBanner>
    <section className="metric-grid compact">{stats.map(([key,label])=><article className="metric-card" key={key}><div className="metric-value">{data?.summary[key] ?? "—"}</div><div className="metric-label">{label}</div></article>)}</section>
    <section className="section-heading"><div><p className="kicker">A. 既有岗位能力变化</p><h2>同一岗位早期与近期对比</h2></div><TrendingUp/></section>
    <div className="change-card-grid">{data?.capability_changes.map(item=><article className="panel change-card evolution-card" key={item.job_title}><div className="candidate-top"><span>既有岗位</span><em className="confidence medium">{item.sample_insufficient?"变化线索":item.trend}</em></div><h2>{item.job_title}</h2><div className="period-compare"><div><small>{item.early_period.label}</small><b>{item.early_period.jd_count}</b><span>JD · {item.early_period.company_count} 家企业</span></div><ArrowRight/><div><small>{item.recent_period.label}</small><b>{item.recent_period.jd_count}</b><span>JD · {item.recent_period.company_count} 家企业</span></div></div><StatusBanner tone={item.sample_insufficient?"warning":"info"}>{item.sample_status}</StatusBanner><h4>近期出现的新能力线索</h4><TagList values={item.skill_changes.filter(s=>s.early_count===0&&s.recent_count>0).map(s=>s.skill_name)} empty="暂无新增线索"/><div className="skill-shift-list">{item.skill_changes.filter(s=>s.early_count!==s.recent_count).slice(0,6).map(s=><span key={s.skill_name}><b>{s.skill_name}</b><small>{s.early_count} → {s.recent_count} 次</small></span>)}</div><p className="evidence-copy">Evidence：{item.support_jd_ids.join("、") || "暂无"}</p></article>)}</div>
    <section className="section-heading"><div><p className="kicker">B. 新岗位发现</p><h2>首次观察后的岗位快照</h2></div><Sparkles/></section>
    <StatusBanner tone="warning">新兴岗位数据当前只有一个有效观察窗口，因此展示首次观察与当前证据规模，不虚构历史增长。</StatusBanner>
    <div className="change-card-grid">{data?.emerging_jobs.map(item=><article className="panel change-card" key={item.candidate_id}><div className="candidate-top"><span>{item.candidate_id}</span><em className="confidence medium">{item.status}</em></div><h2>{item.candidate_name}</h2><p><b>首次观察：</b>{item.first_seen || "暂无"}</p><div className="candidate-stats"><span>{item.jd_count}<small>当前JD</small></span><span>{item.company_count}<small>当前企业</small></span><span>{item.source_count}<small>当前来源</small></span></div><h4>当前核心能力</h4><TagList values={item.core_skills.slice(0,6)}/><button onClick={()=>setSelected(item)}>查看定义与证据 <ArrowRight size={14}/></button></article>)}</div>
    <section className="section-heading"><div><p className="kicker">C / D. 图谱变化</p><h2>新增技能与关系已进入动态能力图谱</h2></div><Network/></section><article className="panel graph-change-callout"><GitBranch/><div><b>Graph V1 → {data?.graph_version || "Graph V2"}</b><p>新增岗位、技能与岗位—技能关系均带 NEW 标记；已有关系收到新 Evidence 时带 UPDATED 标记。</p></div><Link className="primary-button" to="/graph">查看动态图谱</Link></article>
    <article className="panel"><div className="panel-title"><span>多源交叉证据链</span><small>JD为核心证据，政策/报告仅作佐证</small></div><div className="evidence-table">{data?.cross_validation.map(item=><div className="evidence-chain" key={item.trend}><b>{item.trend}</b><span>JD {item.jd_evidence_ids.length} 条 + 政策 {item.policy_evidence_ids.length} 条 + 行业报告 {item.report_evidence_ids.length} 条</span><small>{item.summary}</small><em>综合证据强度：{item.strength}</em></div>)}</div></article>
    {selected?<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p className="kicker">{selected.candidate_id} · {selected.status}</p><h1>{selected.candidate_name}</h1><h3>数据证据</h3><p>招聘JD {selected.jd_count} 条 · 企业 {selected.company_count} 家 · 来源 {selected.source_count} 个</p><h3>时间</h3><p>首次发现 {selected.first_seen || "暂无数据"} · 最近出现 {selected.last_seen || "暂无数据"}</p><h3>核心技能</h3><TagList values={selected.core_skills}/><h3>差异技能</h3><TagList values={selected.distinguishing_skills}/><h3>相似既有岗位</h3><TagList values={selected.similar_existing_jobs}/><StatusBanner tone="warning">{selected.notice}</StatusBanner></aside></div>:null}
  </>;
}
