import SkillEvidenceView from "../components/SkillEvidenceView";
import { emptyForm, resumePayload } from "../formPayloads";
import { FormEvent, useState } from "react";
import { FileCheck2, LoaderCircle } from "lucide-react";
import { postJson } from "../api";
import { PageIntro, StatusBanner } from "../components/Layout";
import type { SkillEvidence } from "../types";

type Result = { resume_id: string; target_job: string; education: string; experience: string; work_experience: string; projects: string[]; skills: SkillEvidence[]; need_human_review: boolean };
const example = { target_job: "AI Agent开发工程师", education: "硕士，人工智能", experience: "2年", work_experience: "负责企业智能体平台研发，使用Python和FastAPI构建后端服务。", projects: "使用LangGraph构建客服Agent，集成RAG知识库、MCP工具调用与向量数据库，并通过Docker部署。", skills_raw: "Python、LangGraph、RAG、MCP、FastAPI、Docker、向量数据库、Prompt Engineering" };
export default function ResumeParsePage() {
  const [form, setForm] = useState(() => emptyForm(example)); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { setResult(await postJson<Result>("/api/resume/parse", resumePayload(form, form.target_job))); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } };
  return <><PageIntro kicker="文本简历 · 能力画像 · Evidence输出" title="简历智能分析" description="以稳定文本输入解析学历、经验、项目和标准技能能力。" index="07" /><div className="workbench-grid"><form className="panel form-panel" onSubmit={submit}><div className="panel-title"><span>简历输入</span><small>文本模式</small></div><div className="form-row"><label>目标岗位<input value={form.target_job} onChange={(event) => setForm({ ...form, target_job: event.target.value })} /></label><label>学历<input value={form.education} onChange={(event) => setForm({ ...form, education: event.target.value })} /></label></div><label>工作经验<input value={form.experience} onChange={(event) => setForm({ ...form, experience: event.target.value })} /></label><label>工作经历<textarea rows={5} value={form.work_experience} onChange={(event) => setForm({ ...form, work_experience: event.target.value })} /></label><label>项目经历<textarea rows={6} value={form.projects} onChange={(event) => setForm({ ...form, projects: event.target.value })} /></label><label>技能清单<textarea rows={4} value={form.skills_raw} onChange={(event) => setForm({ ...form, skills_raw: event.target.value })} /></label><button type="button" disabled={loading} onClick={() => { setForm({ ...example }); setResult(null); setError(""); }}>加载示例</button><button type="button" disabled={loading} onClick={() => { setForm(emptyForm(example)); setResult(null); setError(""); }}>清空</button><button className="primary-button" disabled={loading}>{loading ? <LoaderCircle className="spin" /> : <FileCheck2 />}分析简历</button>{error ? <StatusBanner tone="error">{error}</StatusBanner> : null}</form><article className="panel result-panel"><div className="panel-title"><span>能力画像</span><small>标准技能体系</small></div>{result ? <><div className="profile-header"><div className="avatar-block">CV</div><div><h2>{result.target_job || "未指定目标岗位"}</h2><p>{result.education || "学历信息不足 / 待补充"} · {result.experience || "经验信息不足 / 待补充"}</p></div></div><h3>项目经历</h3><ol className="detail-list">{result.projects.map((item) => <li key={item}>{item}</li>)}</ol><SkillEvidenceView skills={result.skills} /><StatusBanner tone={result.need_human_review ? "warning" : "info"}>{result.need_human_review ? "存在低确定性信息，建议人工复核" : "已按文本证据解析，不代表实际能力认证"}</StatusBanner></> : <div className="empty-state">提交简历文本后，能力画像与技能Evidence将在这里显示。</div>}</article></div></>;
}

